# Generated by Django 2.2.3 on 2019-07-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getintouch',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
