# Generated by Django 2.2.3 on 2019-07-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_getintouch_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='getintouch',
            name='language',
            field=models.CharField(default='en', max_length=4),
        ),
    ]
